title:            Christian Charukiewicz
description:      A personal website.
url:              http://charukiewicz.com
signoff:          # Your name.
disqus_shortname: charukiewicz
facebook_appid:   340993159382119
google_analytics: UA-52843414-1

links:
  - name:         Return ↵
    url:          /
  - name:         Info
    url:          /about
  - name:         Résumé
    url:          /resume
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
