title:            Christian Charukiewicz
description:      A personal website.
url:              http://charukiewicz.com
signoff:          # Your name.
disqus_shortname: charukiewicz
facebook_appid:   340993159382119
google_analytics: UA-52843414-1

links:
  - name:         About
    url:          /about
  - name:         Email
    url:          mailto:c.charukiewicz@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/charukiewicz
    external:     true
  - name:         Linkedin
    url:          https://www.linkedin.com/in/charukiewicz
  - name:         Twitter
    url:          https://www.twitter.com/charukiewicz
    external:     true
  - name:         Résumé
    url:          /files/charukiewicz_resume.pdf
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
